version: '3.3'

services:
  webapi:
    container_name: beam_webapi
    build:
      context: .
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - "db"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: "host=db;port=5432;database=scooters;username=beam;password=beam"
    restart: always

  db:
    image: postgres:12.1
    container_name: scooter_db
    volumes:
      - test_db:/var/lib/postgresql/data/beam
    restart: always
    environment:
      POSTGRES_USER: "beam"
      POSTGRES_PASSWORD: "beam"
      POSTGRES_DB: "scooters"
      PGDATA: /var/lib/postgresql/data/beam

volumes:
  test_db:
    external: true