version: '3.3'

services:
  webapi:
    container_name: beam_webapi
    build: .
    ports:
      - 5000:5000
      - 5001:5001
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=scooters;Username=beam;Password=beam"
    restart: always

  db:
    image: postgres:12.1
    container_name: scooter_db
    volumes:
      - test_db:/var/lib/postgresql/data/beam
    restart: always
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
      POSTGRES_USER: "beam"
      POSTGRES_PASSWORD: "beam"
      POSTGRES_DB: "scooters"
      PGDATA: /var/lib/postgresql/data/beam

volumes:
  test_db:
    external: true